#!/usr/bin/env python3
"""Generate additional company profile pages."""

import os, sys, json

script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

from nav_config import BASE_URL
from templates import get_html_head, get_header_html, get_footer_html, get_mobile_nav_js, get_signup_js, get_cta_box, get_related_links

SITE_DIR = os.path.join(os.path.dirname(script_dir), 'site')

COMPANIES = [
    {
        "slug": "google-deepmind", "name": "Google / DeepMind", "meta_title": "FDE at Google DeepMind", "hq": "Mountain View / London", "fde_count": "30+", "salary": "$170,000 - $280,000",
        "overview": "Google deploys Forward Deployed Engineers through Google Cloud and DeepMind's enterprise partnerships. Google Cloud FDEs help enterprise customers adopt GCP services, Vertex AI, and BigQuery. DeepMind FDEs deploy leading-edge AI research into production applications for Alphabet's partners and selected enterprise customers. The FDE title at Google is relatively new. most equivalent roles were previously called 'Customer Engineer' or 'Solutions Architect'. but Google has started adopting FDE terminology for AI-focused deployment roles as the industry standardizes around the title.",
        "what_fdes_do": "Google Cloud FDEs architect and deploy AI/ML solutions on Vertex AI, design data analytics pipelines on BigQuery, and integrate GCP services into enterprise customer infrastructure. DeepMind FDEs take research models and deploy them in production environments for healthcare (AlphaFold applications), energy optimization, and scientific computing partners. The work is more research-adjacent than at most FDE-hiring companies. Google FDEs benefit from access to Google's internal tools, TPU infrastructure, and world-class ML research.",
        "tech_stack": "Python, Go, SQL, Google Cloud Platform (Vertex AI, BigQuery, Cloud Functions, GKE), TensorFlow, JAX, Kubernetes, Terraform, gRPC. Google's internal tools (Borg, Spanner, Bigtable concepts) influence how FDEs think about system design. DeepMind FDEs additionally work with research ML frameworks and specialized hardware (TPUs).",
        "interview": "Google FDE interviews follow the standard Google engineering interview format: 2 coding rounds (medium-hard LeetCode), 1 system design, 1 behavioral ('Googleyness'), plus an FDE-specific customer scenario round. The process takes 4-6 weeks including committee review. Google's hiring bar is high even by FDE standards. The customer scenario round evaluates how you'd design and deploy a GCP solution for a specific enterprise use case.",
        "culture": "Google's scale means FDE teams have access to unparalleled infrastructure, training resources, and technical mentorship. Work-life balance is generally better than at startups. Compensation is at the top of the market with liquid RSUs (GOOG stock). The trade-off: less autonomy than at a startup. Google's processes, code review standards, and deployment procedures are thorough but can feel slow compared to smaller FDE teams. DeepMind has a more research-oriented culture with academic publication expectations.",
        "faq": [
            {"q": "Does Google use the FDE title officially?", "a": "Google is transitioning. Traditional 'Customer Engineer' and 'Solutions Architect' roles at Google Cloud increasingly align with the FDE model, especially for AI deployment work. Some teams explicitly use the FDE title. DeepMind has used forward-deployment language for their enterprise partnership engineers. Check Google's career page for both 'Forward Deployed Engineer' and 'Customer Engineer' listings."},
            {"q": "What is Google FDE salary?", "a": "Google FDE (and FDE-equivalent) base salaries range from $170,000 to $280,000 depending on level and location. Total compensation including RSUs and bonus can reach $350,000-$500,000+ at senior levels. Google stock is liquid (publicly traded), making the equity component more predictable than pre-IPO company grants."},
            {"q": "How does Google Cloud FDE differ from AWS Solutions Architect?", "a": "Google Cloud FDEs are more hands-on with code: they build custom solutions, write deployment automation, and maintain production systems at customer sites. AWS Solutions Architects are more design-focused: creating reference architectures, running workshops, and advising on best practices. Google's role is closer to the Palantir FDE model than the traditional cloud SA model."},
            {"q": "Can I work at DeepMind as an FDE?", "a": "DeepMind hires engineers for deployment roles, though the exact title varies. These roles deploy DeepMind's research (AlphaFold, weather prediction, energy optimization) into production applications. The bar is extremely high: you need strong ML engineering skills plus deployment experience. DeepMind FDE-equivalent roles are primarily in London with some positions in Mountain View."},
            {"q": "Is Google FDE harder to get into than Palantir FDE?", "a": "The interview processes are comparably difficult but test different skills. Google's coding rounds are more algorithmically challenging (LeetCode medium-hard). Palantir's deployment exercise is more practically demanding (build an analytical application in real-time). Google's committee review process adds time and unpredictability. Both have ~10-15% offer rates for FDE roles."},
        ],
    },
    {
        "slug": "elevenlabs", "name": "ElevenLabs", "hq": "New York / Remote", "fde_count": "5-10", "salary": "$160,000 - $240,000",
        "overview": "ElevenLabs is a leading AI voice synthesis company. Their FDEs deploy custom voice AI solutions for enterprise customers: media companies, gaming studios, accessibility platforms, and customer service operations. ElevenLabs' FDE team is small but growing fast as the company expands from consumer voice cloning to enterprise voice AI infrastructure. The role combines audio engineering domain knowledge with traditional FDE skills.",
        "what_fdes_do": "ElevenLabs FDEs build custom voice AI integrations for enterprise clients. Typical work includes: deploying real-time voice synthesis APIs in customer applications, building custom voice models for specific use cases (character voices for games, branded voices for customer service), integrating voice AI with existing customer workflows (IVR systems, content production pipelines), and optimizing latency and quality for production voice applications. The work is uniquely creative compared to most FDE roles.",
        "tech_stack": "Python, TypeScript, ElevenLabs API, WebSockets (for real-time streaming), audio processing libraries, Docker, cloud infrastructure (AWS/GCP). FDEs need comfort with audio data: sample rates, codecs, latency optimization, and voice quality evaluation. ML knowledge (voice synthesis, TTS models) is helpful but not required at the same depth as research roles.",
        "interview": "ElevenLabs FDE interviews are 4 rounds: recruiter screen, coding (practical API and streaming work), system design (voice AI deployment scenario), and a customer scenario plus team fit round. The company moves fast (2 weeks to offer). They look for engineers who can ship quickly and are excited about voice AI specifically. Demonstrating familiarity with the ElevenLabs product in the interview is a strong signal.",
        "culture": "Fast-moving startup culture with a small, tight-knit team. ElevenLabs has raised significant funding and is growing rapidly. FDEs have high autonomy and direct impact on enterprise revenue. The team is distributed (NYC and remote). Work-life balance depends on customer deployment intensity. Compensation includes meaningful pre-IPO equity.",
        "faq": [
            {"q": "Do I need audio engineering experience for ElevenLabs FDE?", "a": "Not required but helpful. ElevenLabs trains FDEs on voice AI specifics. Strong software engineering skills plus interest in audio/voice technology is sufficient. If you've worked with audio APIs, real-time streaming, or media processing, highlight that experience."},
            {"q": "What is ElevenLabs FDE salary?", "a": "Base salary ranges from $160,000 to $240,000. Total compensation including pre-IPO equity can be significant given ElevenLabs' rapid growth and high valuation. Early FDE hires stand to benefit most from equity appreciation."},
            {"q": "Is ElevenLabs FDE remote?", "a": "Yes, ElevenLabs offers remote FDE positions. The company is distributed by design. Some customer deployments may require periodic travel, but fully remote work is supported. This makes ElevenLabs one of the more remote-friendly FDE employers."},
            {"q": "How does ElevenLabs FDE compare to OpenAI FDE?", "a": "Both deploy AI products for enterprise customers. ElevenLabs FDEs specialize in voice AI (synthesis, cloning, real-time streaming). OpenAI FDEs work with language models (ChatGPT Enterprise, custom GPTs, RAG). ElevenLabs is smaller (more startup energy, more autonomy) while OpenAI is larger (more structure, higher compensation). If voice/audio AI excites you specifically, ElevenLabs is the better fit."},
            {"q": "What types of customers do ElevenLabs FDEs work with?", "a": "Media and entertainment companies (character voices for games and films), customer service platforms (AI voice agents), accessibility organizations (text-to-speech for visually impaired users), content creators (podcast and audiobook production), and enterprise communication platforms. The customer diversity means FDEs see a wide range of deployment scenarios."},
        ],
    },
    {
        "slug": "anduril", "name": "Anduril", "hq": "Costa Mesa, CA", "fde_count": "15-25", "salary": "$155,000 - $250,000",
        "overview": "Anduril builds defense technology: autonomous systems, sensor towers, underwater drones, and AI-powered command-and-control platforms for the US military and allied nations. Anduril FDEs deploy these systems in operational military environments, making this the most physically deployed FDE role in the industry. You might find yourself at a military base, a border installation, or aboard a naval vessel. Anduril's FDE work has real national security implications.",
        "what_fdes_do": "Anduril FDEs deploy Lattice (the company's AI operating system for defense) and hardware platforms at military customer sites. Work includes: integrating Lattice with existing military command-and-control systems, deploying autonomous surveillance towers at border installations, configuring AI-powered threat detection and classification systems, training military operators on Anduril platforms, and providing on-site technical support during operational exercises. The hardware component makes Anduril FDE unique: you'll work with physical devices, sensors, and communications systems, not just software.",
        "tech_stack": "C++, Python, Rust, Linux, networking (mesh networks, radio communications), Lattice platform, Docker/Kubernetes, sensor integration, real-time systems, edge computing. FDEs need comfort with hardware-software integration, field-deployable systems, and environments without reliable internet connectivity. Security clearance required for most roles.",
        "interview": "Anduril FDE interviews include: recruiter screen, coding (C++/Python, systems-focused), system design (distributed sensor network or edge computing scenario), and a behavioral round focused on mission alignment and ability to work in austere environments. Security clearance eligibility is verified early. Anduril values engineers who are motivated by the defense mission and can operate independently in field conditions.",
        "culture": "Mission-driven culture with a defense-tech startup mentality. Anduril combines Silicon Valley engineering practices with military operational discipline. FDE travel is significant: deployments at military bases, border installations, and allied nation sites. Some deployments are in remote or austere locations. Compensation is competitive, and the mission resonance attracts engineers who want their work to have national security impact. Work-life balance varies by deployment intensity.",
        "faq": [
            {"q": "Does Anduril FDE require a security clearance?", "a": "Yes. Most Anduril FDE roles require an active or obtainable US security clearance (Secret or Top Secret). US citizenship is required. The clearance process takes 3-12 months for initial clearance. Anduril sponsors the clearance process. Having an existing clearance significantly accelerates hiring."},
            {"q": "What is Anduril FDE salary?", "a": "Base salary ranges from $155,000 to $250,000 depending on seniority and clearance level. Total compensation including equity can be significant: Anduril is a private company valued at $14B+ with substantial DoD contracts. Deployment bonuses may apply for extended field work. Compensation is competitive with non-defense FDE roles despite the additional clearance and travel requirements."},
            {"q": "How much travel do Anduril FDEs do?", "a": "More than most FDE roles: 40-60%. Deployments can last weeks to months at military installations. Some are domestic (US military bases, border sites) and some are international (allied nation deployments). The travel is more physically demanding than typical FDE travel: field conditions, limited amenities, and sometimes restricted communication. This is the most 'deployed' FDE role in the literal sense."},
            {"q": "Do I need military experience for Anduril FDE?", "a": "Not required but valued. Anduril hires from both military and civilian engineering backgrounds. Military experience helps with understanding operational requirements, military terminology, and working within DoD acquisition frameworks. Civilian engineers with strong software skills and willingness to work in field conditions are equally competitive. What matters most is engineering ability and mission motivation."},
            {"q": "How does Anduril FDE compare to Palantir FDE?", "a": "Both serve government and defense customers. Palantir FDEs deploy analytics software (Foundry/Gotham) primarily on screens in offices. Anduril FDEs deploy hardware and software systems in operational environments: borders, military bases, naval vessels. Anduril is more physically hands-on. Palantir is more data-analytics-focused. Both require clearances. Anduril's hardware component makes it uniquely tangible among FDE roles."},
        ],
    },
    {
        "slug": "servicenow", "name": "ServiceNow", "hq": "Santa Clara, CA", "fde_count": "20+", "salary": "$160,000 - $240,000",
        "overview": "ServiceNow FDEs deploy the company's AI-powered workflow automation platform for enterprise IT, customer service, and HR operations. ServiceNow is a $150B+ public company with 8,000+ enterprise customers. Their FDE team focuses on deploying Now Assist (ServiceNow's generative AI layer) and custom workflow automations that go beyond standard platform configuration. As enterprises adopt AI-powered ITSM and workflow automation, ServiceNow FDEs bridge the gap between platform capabilities and customer-specific operational requirements.",
        "what_fdes_do": "ServiceNow FDEs build custom workflow automations, deploy Now Assist AI features, and integrate ServiceNow with customer IT ecosystems. Typical projects include: automating incident management with AI-powered triage and resolution, building custom integrations between ServiceNow and customer monitoring tools (Splunk, Datadog, PagerDuty), deploying employee self-service portals with natural language processing, and configuring AI-powered knowledge management systems. The role requires understanding enterprise IT operations (ITSM, ITOM) alongside software engineering skills.",
        "tech_stack": "JavaScript (ServiceNow scripting), Python, ServiceNow platform (Flow Designer, Integration Hub, Now Assist), REST APIs, CMDB, ITIL frameworks, SQL, ServiceNow's proprietary scripting environment. FDEs need to learn ServiceNow's platform deeply. Prior ServiceNow experience is a strong advantage. Familiarity with ITSM concepts (incident management, change management, CMDB) differentiates strong candidates.",
        "interview": "ServiceNow FDE interviews are 4-5 rounds: recruiter screen, coding (JavaScript/Python, platform-relevant), system design (enterprise workflow automation scenario), customer scenario, and values/team fit. ServiceNow values customer obsession and platform expertise. Prior ServiceNow experience accelerates the process. The interview is less algorithmically challenging than Palantir or Google but places heavy emphasis on enterprise IT domain knowledge.",
        "culture": "ServiceNow has a mature enterprise software culture: structured career ladders, formal training programs, and comprehensive benefits. The company's 'hunger to make customers successful' culture translates directly to FDE work. Travel is moderate (20-30%). Work-life balance is generally good compared to startup FDE roles. Compensation includes competitive base salary plus liquid RSUs (NOW stock). ServiceNow's FDE program is well-resourced with documentation, playbooks, and senior mentorship.",
        "faq": [
            {"q": "Do I need ServiceNow experience for this FDE role?", "a": "Not strictly required but strongly preferred. ServiceNow's platform has its own scripting language, workflow engine, and architecture. Candidates with ServiceNow Administrator or Developer certifications skip the platform learning curve. If you don't have ServiceNow experience, strong JavaScript skills and familiarity with enterprise IT concepts (ITSM, ITIL) are the best substitutes."},
            {"q": "What is ServiceNow FDE salary?", "a": "Base salary ranges from $160,000 to $240,000. Total compensation including RSUs (NOW stock, publicly traded at ~$800/share) and bonus can reach $300,000-$400,000+ at senior levels. ServiceNow's compensation is competitive with other large enterprise software companies and more predictable than startup equity."},
            {"q": "How does ServiceNow FDE compare to Salesforce FDE?", "a": "Both deploy enterprise platforms for large customers. ServiceNow FDEs focus on IT operations and workflow automation. Salesforce FDEs focus on CRM, sales, and Agentforce AI. ServiceNow's platform is more technical (scripting-heavy) while Salesforce's is more configuration-heavy. ServiceNow's FDE program is smaller and more established. Salesforce's is larger and rapidly scaling. Both offer strong compensation and career progression at public companies."},
            {"q": "Is ServiceNow FDE good for career growth?", "a": "Yes. ServiceNow's enterprise IT platform is used by 85% of the Fortune 500. FDE experience at ServiceNow opens doors to IT leadership, enterprise architecture, and platform consulting roles. The ITSM/ITOM domain knowledge is transferable to any company that runs enterprise IT operations. ServiceNow FDEs who develop deep platform expertise are highly sought after by ServiceNow partners and customers."},
            {"q": "Does ServiceNow hire remote FDEs?", "a": "ServiceNow offers hybrid FDE positions at major office locations (Santa Clara, San Diego, Orlando, Chicago) and some remote roles. Remote FDE positions require periodic travel to customer sites (20-30%). The company supports flexible work arrangements. Fully remote with zero travel is less common but available for some positions."},
        ],
    },
    {
        "slug": "cohere", "name": "Cohere", "hq": "Toronto / San Francisco", "fde_count": "10-15", "salary": "$160,000 - $235,000",
        "overview": "Cohere builds enterprise-grade large language models for search, RAG, and text generation. Their FDEs deploy Cohere's models inside enterprise environments, focusing on use cases where privacy, data sovereignty, and on-premise deployment matter. Cohere differentiates from OpenAI by offering models that run on customer infrastructure (not just cloud APIs), making the FDE role critical for customers who can't send data to external APIs. This on-premise deployment complexity is exactly what FDEs solve.",
        "what_fdes_do": "Cohere FDEs deploy language models in customer environments: building RAG systems over proprietary documents, integrating Cohere's search capabilities into customer products, deploying on-premise model instances for customers with data sovereignty requirements, fine-tuning models for specific industry vocabulary and use cases, and building evaluation frameworks that measure model performance on customer-specific benchmarks. The on-premise deployment work is technically demanding: optimizing model inference on customer hardware, managing GPU resources, and ensuring model performance in environments without internet access.",
        "tech_stack": "Python, Cohere API and SDK, vector databases (Weaviate, Qdrant), Docker, Kubernetes, NVIDIA GPU infrastructure, model serving frameworks (vLLM, TensorRT), cloud platforms (AWS, GCP, Azure), on-premise deployment tools. FDEs need strong understanding of LLM inference: tokenization, embedding models, reranking, and retrieval-augmented generation architecture. Hardware-aware optimization (GPU utilization, batch inference, quantization) differentiates senior candidates.",
        "interview": "Cohere FDE interviews are 4 rounds: recruiter screen, coding (Python, LLM-focused), system design (RAG or on-premise deployment scenario), and customer scenario plus team fit. Cohere values engineers who understand LLM fundamentals beyond API calls: how models work, why certain architectures perform better for specific use cases, and how to evaluate model quality. The interview is technically demanding but the team is collaborative and the process moves in 2-3 weeks.",
        "culture": "Research-informed engineering culture based in Toronto (Canada's AI hub) with a growing SF office. Cohere's team includes former Google Brain researchers alongside practical deployment engineers. FDEs benefit from proximity to leading-edge LLM research while doing hands-on customer work. The company is smaller than OpenAI (more startup energy) but well-funded. Remote-friendly with distributed teams across Toronto, SF, and London. Compensation includes pre-IPO equity with significant upside potential.",
        "faq": [
            {"q": "How does Cohere FDE differ from OpenAI FDE?", "a": "Cohere FDEs do more on-premise deployment work. OpenAI's enterprise product is primarily cloud-based (API). Cohere offers models that run on customer infrastructure, which creates unique deployment challenges: GPU optimization, on-premise security, air-gapped environments. If you want to work at the infrastructure level of AI deployment (not just API integration), Cohere's FDE role goes deeper technically."},
            {"q": "What is Cohere FDE salary?", "a": "Base salary ranges from $160,000 to $235,000. Toronto-based roles are in CAD (approximately C$200,000-C$310,000). Total compensation including pre-IPO equity can be significant. Cohere has raised $500M+ and is one of the most valuable AI startups. Early equity grants could be very valuable at IPO."},
            {"q": "Is Cohere FDE remote?", "a": "Yes, Cohere is remote-friendly. FDE roles can be based in Toronto, San Francisco, London, or remote. The company's distributed culture supports remote work well. Customer deployments may require periodic travel but the base role is location-flexible. This makes Cohere one of the more accommodating FDE employers for remote workers."},
            {"q": "Do I need ML research experience for Cohere FDE?", "a": "Not research experience, but you need strong LLM practical knowledge. Cohere FDEs should understand: how transformer models work at a high level, RAG architecture design, embedding models vs. generative models, and model evaluation metrics. You don't need to train models from scratch, but you need to understand why certain architectures perform better for specific use cases and how to optimize inference in production."},
            {"q": "Is Toronto or SF better for Cohere FDE?", "a": "Toronto is Cohere's HQ with the largest engineering team and closest proximity to research. SF has a growing office focused on US enterprise customers. Both locations offer strong FDE opportunities. Toronto has lower cost of living, and CAD-denominated salaries go further. SF offers more networking opportunities in the broader AI ecosystem. Remote is also a viable option."},
        ],
    },
    {
        "slug": "posthog", "name": "PostHog", "hq": "Remote (Global)", "fde_count": "5-10", "salary": "$150,000 - $220,000",
        "overview": "PostHog is an open-source product analytics platform. Their FDE model is unique: PostHog FDEs are effectively product engineers who spend 40-60% of their time on customer-facing work. There's no separate 'FDE org'. engineers rotate between core product development and customer deployment support. This makes PostHog's approach the most product-integrated FDE model in the industry and a strong fit for engineers who want to stay close to product development while getting customer exposure.",
        "what_fdes_do": "PostHog FDEs split time between building core product features and supporting enterprise customer deployments. Customer-facing work includes: setting up PostHog for enterprise customers with complex data requirements, building custom analytics dashboards and event tracking architectures, integrating PostHog with customer data stacks (data warehouses, reverse ETL, CDP platforms), and debugging data pipeline issues in customer environments. Product-facing work includes: building features informed by customer feedback, contributing to PostHog's open-source codebase, and improving deployment documentation based on real customer experiences.",
        "tech_stack": "TypeScript, Python, Django, React, PostgreSQL, ClickHouse (analytics database), Kafka, Docker, Kubernetes. PostHog's stack is modern and open-source. FDEs contribute directly to the public codebase. Experience with analytics infrastructure, event tracking, and data warehousing is particularly valuable.",
        "interview": "PostHog's interview is lightweight: 3-4 rounds including a paid work trial (you work on a real PostHog task for 1-2 days, compensated). No LeetCode. They evaluate based on actual code you ship, your communication in async (they're remote-first), and your ability to work autonomously. PostHog's interview process is the most practical and engineer-friendly among FDE-hiring companies.",
        "culture": "Fully remote, async-first company with a transparent culture (public handbook, open-source product, transparent compensation). PostHog is one of the most developer-friendly companies to work for. FDEs have extreme autonomy: you choose what to work on, when to work, and how to split time between product and customer work. The trade-off: less structure than Salesforce or Palantir. You need to be self-directed. Compensation is transparent (public pay calculator) and competitive for a remote-first company.",
        "faq": [
            {"q": "Is PostHog FDE a real FDE role?", "a": "It's the most product-integrated version of FDE. PostHog doesn't have a separate FDE team. engineers naturally split between product development and customer-facing work. The FDE work is real (enterprise deployments, customer integrations), but you're also a product engineer. If you want pure FDE work (100% customer-facing), PostHog isn't the right fit. If you want the best of both worlds, it's ideal."},
            {"q": "What is PostHog FDE salary?", "a": "PostHog uses a transparent compensation calculator based on role, seniority, and location. Base salaries for FDE-equivalent roles range from $150,000 to $220,000 depending on level and location. Equity is included. PostHog's compensation is competitive for a remote-first company, especially when adjusted for non-SF/NYC cost of living."},
            {"q": "Is PostHog fully remote?", "a": "Yes, PostHog is one of the most remote-friendly FDE employers. The company has no offices. All work is async-first. Customer interactions are primarily virtual. Travel to customer sites is minimal. If fully remote with near-zero travel is your top priority, PostHog is one of the best FDE options available."},
            {"q": "Do PostHog FDEs contribute to open source?", "a": "Yes. PostHog's product is open-source, and FDE contributions to the codebase are public. This means your FDE work at PostHog builds a public portfolio of production code contributions. For engineers who value open-source visibility and public technical credibility, this is a unique benefit that other FDE roles (especially at companies like Palantir or OpenAI with proprietary codebases) can't offer."},
            {"q": "How does PostHog FDE compare to Palantir FDE?", "a": "Opposite ends of the FDE spectrum. Palantir: structured program, heavy travel, deep customer embedding, proprietary platform, defense/government customers. PostHog: flat structure, zero travel, split product/customer time, open-source product, tech-company customers. Palantir is best for engineers who want intense customer deployment experience. PostHog is best for engineers who want customer exposure without leaving product development."},
        ],
    },
    {
        "slug": "atlassian", "name": "Atlassian", "hq": "Sydney / San Francisco", "fde_count": "10-20", "salary": "$160,000 - $245,000",
        "overview": "Atlassian (Jira, Confluence, Bitbucket) has begun hiring Forward Deployed Engineers to support enterprise customers adopting Atlassian Intelligence, their AI-powered suite of features. As Atlassian moves from project management tools to an AI-powered enterprise collaboration platform, FDEs help large customers integrate Atlassian products with their development workflows, data systems, and organizational processes at scale.",
        "what_fdes_do": "Atlassian FDEs deploy Atlassian Intelligence features for enterprise customers, build custom integrations between Atlassian products and customer development toolchains (GitHub, GitLab, CI/CD systems, Slack), configure advanced Jira workflows for large engineering organizations, and help customers migrate from legacy project management and documentation systems to Atlassian's platform. The work combines platform configuration expertise with custom integration development.",
        "tech_stack": "Java, TypeScript, Atlassian Forge (app development platform), REST APIs, GraphQL, Atlassian Connect, SQL, cloud platforms (AWS primarily). Familiarity with software development workflows (CI/CD, git, code review) is essential since Atlassian's customers are primarily engineering organizations. Atlassian Forge is a proprietary development framework that FDEs learn on the job.",
        "interview": "Atlassian FDE interviews are 4-5 rounds: recruiter screen, coding (Java or TypeScript), system design (enterprise integration scenario), customer scenario (focused on change management and adoption), and values fit. Atlassian's 'Values' interview evaluates alignment with their five company values including 'Don't #@!% the customer.' The interview process takes 3-4 weeks. The company is known for thoughtful, respectful interviewing.",
        "culture": "Atlassian has a distributed culture with team members across Sydney, San Francisco, Austin, Bangalore, and remote. The company was an early adopter of remote work and maintains a flexible 'Team Anywhere' policy. FDEs work in a mature, well-resourced environment with clear career ladders, professional development budgets, and strong benefits. Work-life balance is among the best in the FDE market. Atlassian is publicly traded (TEAM) with liquid equity compensation.",
        "faq": [
            {"q": "Is Atlassian's FDE program established?", "a": "It's newer than Palantir or Salesforce's programs. Atlassian began hiring FDEs in 2025 as they expanded Atlassian Intelligence for enterprise customers. The program is growing but still early-stage, which means more opportunity to shape the role and influence how FDE work is done at Atlassian. Engineers who join now will help define the FDE playbook for the company."},
            {"q": "What is Atlassian FDE salary?", "a": "Base salary ranges from $160,000 to $245,000 depending on level and location. Total compensation including RSUs (TEAM stock) and bonus can reach $300,000-$400,000 at senior levels. Sydney-based roles are denominated in AUD. Atlassian's compensation is competitive with other large public tech companies."},
            {"q": "Do I need Atlassian product experience?", "a": "Helpful but not required. Most software engineers have used Jira or Confluence, which gives baseline product familiarity. Deep Atlassian platform expertise (Forge, Connect, custom fields, advanced workflows) is a strong differentiator. Atlassian provides training and certification resources for new FDEs. The platform learning curve is moderate. less complex than Salesforce's ecosystem."},
            {"q": "Is Atlassian FDE remote?", "a": "Yes. Atlassian's 'Team Anywhere' policy supports remote and distributed FDE work. The company has offices in Sydney, SF, Austin, NYC, and Bangalore, but remote positions are widely available. Customer work is primarily virtual with optional travel. Atlassian is one of the most remote-friendly large companies hiring FDEs."},
            {"q": "Who are Atlassian's FDE customers?", "a": "Large engineering organizations that use Atlassian products at scale: 500+ person engineering teams, Fortune 500 IT departments, and technology companies standardizing on Atlassian for project management, documentation, and code collaboration. FDEs work with technical stakeholders (engineering managers, DevOps leads, CIOs) rather than non-technical business users, making the role more engineering-focused than some FDE positions."},
        ],
    },
]


def generate_more_company_profiles():
    print("  Generating additional company profiles...")
    count = 0
    for co in COMPANIES:
        related = get_related_links([
            {"href": "/salaries/", "label": "FDE Salary Data"},
            {"href": "/career/forward-deployed-engineer-interview-questions/", "label": "FDE Interview Questions"},
            {"href": "/insights/forward-deployed-engineer-vs-software-engineer/", "label": "FDE vs Software Engineer"},
            {"href": "/career/forward-deployed-engineer-levels/", "label": "FDE Career Levels"},
        ])
        faq_html = ""
        faq_items = []
        for faq in co["faq"]:
            faq_html += '<div style="margin-bottom: 1.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid var(--border);"><h3 style="font-size: 1.15rem; font-weight: 600; color: var(--text-primary); margin-bottom: 0.5rem;">%s</h3><p style="color: var(--text-secondary); line-height: 1.7;">%s</p></div>' % (faq["q"], faq["a"])
            faq_items.append({"@type": "Question", "name": faq["q"], "acceptedAnswer": {"@type": "Answer", "text": faq["a"]}})

        body = '''
        <section class="section" style="max-width: 900px; margin: 0 auto; padding-top: 8rem;">
            <h1 style="font-size: 2.5rem; font-weight: 700; margin-bottom: 0.5rem;">Forward Deployed Engineer at %s</h1>
            <p style="font-size: 1rem; color: var(--text-muted); margin-bottom: 2rem;">%s &middot; %s FDEs &middot; %s</p>
            <div style="color: var(--text-secondary); font-size: 1.05rem; line-height: 1.8;">
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 0 0 1rem;">Overview</h2>
                <p style="margin-bottom: 1.25rem;">%s</p>
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">What FDEs Do at %s</h2>
                <p style="margin-bottom: 1.25rem;">%s</p>
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">Tech Stack</h2>
                <p style="margin-bottom: 1.25rem;">%s</p>
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">Interview Process</h2>
                <p style="margin-bottom: 1.25rem;">%s</p>
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">Culture & Work-Life</h2>
                <p style="margin-bottom: 1.25rem;">%s</p>
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">Frequently Asked Questions</h2>
                %s
            </div>
            %s

            %s
        </section>
''' % (co["name"], co["hq"], co["fde_count"], co["salary"], co["overview"], co["name"], co["what_fdes_do"], co["tech_stack"], co["interview"], co["culture"], faq_html, related, get_cta_box())

        faq_schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faq_items}, indent=2)
        breadcrumb = json.dumps({"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL},
            {"@type": "ListItem", "position": 2, "name": "Companies", "item": BASE_URL + "/companies/"},
            {"@type": "ListItem", "position": 3, "name": co["name"], "item": BASE_URL + "/companies/" + co["slug"] + "/"}
        ]}, indent=2)

        extra_head = '<script type="application/ld+json">\n' + faq_schema + '\n    </script>\n    <script type="application/ld+json">\n' + breadcrumb + '\n    </script>'

        html = get_html_head(
            title=co.get("meta_title", "FDE at " + co["name"] + ": Salary, Interview, Role"),
            description="Forward Deployed Engineer at " + co["name"] + ". " + co["salary"] + " salary, interview process, tech stack, and what FDEs do.",
            canonical_path="/companies/" + co["slug"] + "/",
            extra_head=extra_head
        )
        html += "\n<body>\n" + get_header_html() + "\n    <main>\n" + body + "\n    </main>\n" + get_footer_html() + get_mobile_nav_js() + get_signup_js() + "\n</body>\n</html>"

        out_dir = os.path.join(SITE_DIR, 'companies', co['slug'])
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(html)
        count += 1
    print("  " + str(count) + " additional company profiles generated")


if __name__ == "__main__":
    generate_more_company_profiles()
