#!/usr/bin/env python3
"""
Generate company-specific FDE profile pages from jobs.json data.
pSEO Profiles playbook. Targets "[company] forward deployed engineer" queries.
Min 1,200 words per page.
"""

import os
import sys
import json
import re
import hashlib
from collections import Counter
from statistics import median as stat_median

script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

from nav_config import SITE_NAME, BASE_URL
from templates import (
    get_html_head, get_header_html, get_footer_html,
    get_mobile_nav_js, get_signup_js, get_cta_box, get_related_links
)

SITE_DIR = os.path.join(os.path.dirname(script_dir), 'site')
DATA_DIR = os.path.join(os.path.dirname(script_dir), 'data')

# Curated profiles for top companies (kept from original)
CURATED = {
    "palantir", "openai", "anthropic", "salesforce", "databricks",
    "scale-ai", "ramp", "rippling",
}

# Pages already generated by generate_more_company_profiles.py
ALREADY_GENERATED = {
    "anduril", "atlassian", "cohere", "elevenlabs", "google-deepmind",
    "posthog", "servicenow",
}


# duplicated from generate_jobs_page.py -- keep in sync
def derive_seniority(title):
    t = title or ''
    t_lower = t.lower()
    if re.search(r'\b(manager|director|head of|vp|lead)\b', t_lower):
        return 'lead'
    if re.search(r'\b(senior|sr\.|sr |staff|principal)\b', t_lower):
        return 'senior'
    if re.search(r'\b(junior|jr\.|associate|entry|intern|analyst)\b', t_lower):
        return 'junior'
    return 'mid'


def make_slug(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def make_job_slug(company, title, source_url):
    text = company + '-' + title
    base = re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')[:80]
    hash_input = source_url or (company + title)
    hash6 = hashlib.md5(hash_input.encode()).hexdigest()[:6]
    return base + '-' + hash6


def format_k(amount):
    if not amount or amount <= 0:
        return None
    return '$' + str(int(round(amount / 1000))) + 'K'


def extract_company_blurb(description, company_name):
    """Extract first 2 paragraphs that mention the company, or return None."""
    if not description:
        return None
    paragraphs = [p.strip() for p in description.split('\n\n') if p.strip()]
    company_lower = company_name.lower()
    matches = []
    for p in paragraphs:
        if company_lower in p.lower() and len(p) > 80:
            matches.append(p[:600])
            if len(matches) == 2:
                break
    return ' '.join(matches) if matches else None


def generate_data_driven_profile(company_name, co_jobs, all_jobs, market_intel):
    """Generate a full company profile page from jobs.json data."""
    slug = make_slug(company_name)
    count = len(co_jobs)
    total_jobs = len(all_jobs)

    # Salary stats
    sal_jobs = [(j.get('min_amount', 0) or 0, j.get('max_amount', 0) or 0)
                for j in co_jobs if (j.get('min_amount', 0) or 0) > 0 and (j.get('max_amount', 0) or 0) > 0]

    if sal_jobs:
        mins = [s[0] for s in sal_jobs]
        maxs = [s[1] for s in sal_jobs]
        all_vals = mins + maxs
        med = int(stat_median(all_vals))
        sal_range = (format_k(min(mins)) or 'N/A') + ' to ' + (format_k(max(maxs)) or 'N/A')
        med_str = format_k(med) or 'N/A'
    else:
        med = 0
        sal_range = 'Not disclosed'
        med_str = 'Not disclosed'

    # Location info
    locations = list(set(
        re.sub(r',\s*(US|USA)$', '', (j.get('location') or '').strip())
        for j in co_jobs
        if (j.get('location') or '').strip() and not (j.get('is_remote', False))
    ))
    locations = [l for l in locations if l]

    remote_count = sum(1 for j in co_jobs if j.get('is_remote', False))
    onsite_count = count - remote_count

    # Extract blurb from first job description
    blurb = None
    for j in co_jobs:
        blurb = extract_company_blurb(j.get('description', ''), company_name)
        if blurb:
            break

    if not blurb:
        loc_str = locations[0] if locations else 'multiple cities'
        blurb = (
            f'{company_name} is currently hiring {count} Forward Deployed Engineer'
            f'{"s" if count != 1 else ""} '
            f'{"across " + ", ".join(locations[:3]) if locations else "in various locations"}. '
            f'The roles {"are" if count != 1 else "is"} part of {company_name}\'s customer engineering function, '
            f'responsible for deploying and customizing the company\'s products directly at customer sites. '
            f'FDE roles at {company_name} require strong software engineering skills combined with the ability '
            f'to work directly with enterprise customers on production deployments.'
        )

    # Job list HTML
    job_list_html = ''
    for j in co_jobs:
        title = j.get('title', 'Forward Deployed Engineer')
        loc = j.get('location', '')
        is_remote = j.get('is_remote', False)
        mn = j.get('min_amount', 0) or 0
        mx = j.get('max_amount', 0) or 0
        source_url = j.get('source_url', '')
        job_slug = make_job_slug(company_name, title, source_url)

        sal_badge = ''
        if mn > 0 and mx > 0:
            sal_badge = f'<span class="cp-job__salary">{format_k(mn)} &ndash; {format_k(mx)}</span>'

        loc_badge = ''
        if is_remote:
            loc_badge = '<span class="cp-job__tag cp-job__tag--remote">Remote</span>'
        elif loc:
            loc_badge = f'<span class="cp-job__tag">{loc}</span>'

        seniority = derive_seniority(title)
        sen_labels = {'lead': 'Manager/Lead', 'senior': 'Senior+', 'mid': 'Mid-level', 'junior': 'Junior'}
        sen_badge = f'<span class="cp-job__tag cp-job__tag--sen">{sen_labels.get(seniority, "Mid-level")}</span>'

        job_list_html += f'''
                <a href="/jobs/{job_slug}/" class="cp-job">
                    <div class="cp-job__header">
                        <div>
                            <div class="cp-job__title">{title}</div>
                        </div>
                        {sal_badge}
                    </div>
                    <div class="cp-job__meta">
                        {loc_badge}
                        {sen_badge}
                        <span class="cp-job__cta">View role &rarr;</span>
                    </div>
                </a>'''

    # Similar companies -- closest by role count
    all_by_company = {}
    for j in all_jobs:
        c = (j.get('company') or '').strip()
        if c:
            all_by_company.setdefault(c, []).append(j)

    sorted_by_count = sorted(all_by_company.items(), key=lambda x: len(x[1]), reverse=True)
    similar = [
        (n, len(js)) for n, js in sorted_by_count
        if n != company_name and make_slug(n) not in CURATED and make_slug(n) not in ALREADY_GENERATED
    ][:5]

    similar_html = ''
    for sim_name, sim_count in similar:
        sim_slug = make_slug(sim_name)
        similar_html += f'''
                <a href="/companies/{sim_slug}/" class="cp-sim-card">
                    <div class="cp-sim-card__name">{sim_name}</div>
                    <div class="cp-sim-card__count">{sim_count} role{"s" if sim_count != 1 else ""}</div>
                </a>'''

    # Tools mentioned in job descriptions
    tools_mentioned = Counter()
    for j in co_jobs:
        for tool in (j.get('tools') or []):
            if isinstance(tool, dict):
                name = tool.get('tool_name', '')
            else:
                name = str(tool)
            if name:
                tools_mentioned[name.strip()] += 1

    # Global tool context
    global_tools = market_intel.get('tools', {})
    total_jobs_for_pct = market_intel.get('total_jobs', total_jobs)

    # Build about section
    loc_str = ', '.join(locations[:3]) if locations else 'various locations'
    if remote_count > 0 and onsite_count > 0:
        work_type = f'{onsite_count} on-site and {remote_count} remote'
    elif remote_count > 0:
        work_type = f'{remote_count} fully remote'
    else:
        work_type = f'{onsite_count} on-site'

    # Tools context for this company
    if tools_mentioned:
        top_tools = [t for t, _ in tools_mentioned.most_common(8)]
        tools_prose = f'Job descriptions for {company_name} FDE roles mention the following tools and technologies: {", ".join(top_tools)}.'
    else:
        # Fall back to global top tools
        top_global = [t for t, _ in sorted(global_tools.items(), key=lambda x: x[1], reverse=True)[:8]]
        tools_prose = f'FDE roles broadly require expertise in: {", ".join(top_global)}. {company_name} postings do not itemize specific tools.'

    # Seniority breakdown for this company
    sen_counts = Counter(derive_seniority(j.get('title', '')) for j in co_jobs)
    sen_prose_parts = []
    for bucket, label in [('lead', 'manager or lead-level'), ('senior', 'senior-level'), ('mid', 'mid-level'), ('junior', 'junior-level')]:
        if sen_counts.get(bucket, 0) > 0:
            sen_prose_parts.append(f'{sen_counts[bucket]} {label}')
    sen_prose = f'The {count} {"role is" if count == 1 else "roles are"} broken down as: {", ".join(sen_prose_parts)}.' if sen_prose_parts else ''

    # Market context
    mkt_segment = market_intel.get('segment', {})
    enterprise_pct = int(round(100 * mkt_segment.get('Enterprise', 0) / total_jobs_for_pct)) if total_jobs_for_pct else 0

    # Build FAQs
    faq_items_data = [
        {
            "q": f"What does a Forward Deployed Engineer do at {company_name}?",
            "a": f"A Forward Deployed Engineer at {company_name} is embedded with enterprise customers to deploy, customize, and maintain the company's products. Based on {count} active FDE {'role' if count == 1 else 'roles'} as of April 30, 2026, these positions are {work_type} and located {'in ' + loc_str if locations else 'across various markets'}. FDEs write production code, design integration architectures, and translate customer feedback into product improvements."
        },
        {
            "q": f"What is the salary range for FDE roles at {company_name}?",
            "a": (
                f"Based on {len(sal_jobs)} of {count} active {company_name} FDE {'posting' if count == 1 else 'postings'} that disclosed compensation, the salary range is {sal_range} with a median of {med_str}. "
                if sal_jobs else
                f"{company_name}'s active FDE postings do not disclose salary ranges. The overall FDE market median is $135,000 based on 111 of 134 postings with disclosed pay. "
            ) + f"Equity is included in most FDE compensation packages at venture-backed and public companies."
        },
        {
            "q": f"How many Forward Deployed Engineers does {company_name} hire?",
            "a": f"{company_name} has {count} active FDE {'posting' if count == 1 else 'postings'} as of April 30, 2026, making {'it' if count == 1 else 'them'} one of {total_jobs} total active FDE roles tracked by FDE Pulse across {len(all_by_company)} companies. {sen_prose}"
        },
        {
            "q": f"What skills are required for {company_name} FDE roles?",
            "a": tools_prose + f" Strong software engineering fundamentals (typically 3 or more years of experience), customer communication skills, and the ability to work independently at client sites are standard requirements across all FDE postings at {company_name}."
        },
        {
            "q": f"How does an FDE role at {company_name} compare to a software engineer role?",
            "a": f"FDE roles at {company_name} differ from internal software engineering in two key ways: customer proximity and deployment scope. FDEs work directly at customer sites or in close coordination with customer teams, building solutions on top of {company_name}'s platform rather than contributing to the core product. This requires stronger communication skills and higher tolerance for ambiguity than most product engineering roles. Compensation typically reflects this premium: the FDE market median is $135,000 base across 134 active postings."
        },
    ]

    faq_html = ''
    faq_schema_list = []
    for fq in faq_items_data:
        faq_html += f'''
                <div style="margin-bottom: 1.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid var(--border);">
                    <h3 style="font-size: 1.15rem; font-weight: 600; color: var(--text-primary); margin-bottom: 0.5rem;">{fq["q"]}</h3>
                    <p style="color: var(--text-secondary); line-height: 1.7;">{fq["a"]}</p>
                </div>'''
        faq_schema_list.append({
            "@type": "Question",
            "name": fq["q"],
            "acceptedAnswer": {"@type": "Answer", "text": fq["a"]}
        })

    related = get_related_links([
        {"href": "/salaries/", "label": "FDE Salary Data"},
        {"href": "/companies/", "label": "All Companies Hiring FDEs"},
        {"href": "/jobs/", "label": "Browse All FDE Jobs"},
        {"href": "/insights/fde-hiring-trends-2026/", "label": "FDE Hiring Trends 2026"},
        {"href": "/insights/fde-salary-benchmarks/", "label": "FDE Salary Benchmarks"},
    ])

    # ── Extended prose (pad to 1200+ words) ─────────────────────────────────────
    geo_focus = market_intel.get('geo_focus', {})
    na_pct = int(round(100 * geo_focus.get('North America', 0) / total_jobs_for_pct)) if total_jobs_for_pct else 0

    hiring_signals = market_intel.get('hiring_signals', {})
    growth_pct = int(round(100 * hiring_signals.get('Growth Hire', 0) / total_jobs_for_pct)) if total_jobs_for_pct else 0

    team_structure = market_intel.get('team_structure', {})
    build_team_pct = int(round(100 * team_structure.get('Build Team', 0) / total_jobs_for_pct)) if total_jobs_for_pct else 0
    first_hire_pct = int(round(100 * team_structure.get('First Hire', 0) / total_jobs_for_pct)) if total_jobs_for_pct else 0

    about_fde = f'''
                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">About Forward Deployed Engineering at {company_name}</h2>

                <p style="margin-bottom: 1.25rem;">{blurb}</p>

                <p style="margin-bottom: 1.25rem;">Companies like {company_name} typically structure FDE teams around a build-team model, where engineers join an existing customer engineering function and deploy the product across a portfolio of accounts. Based on FDE Pulse data across {total_jobs} active postings, {build_team_pct}% of FDE roles are build-team positions and {first_hire_pct}% are "first hire" situations where the engineer defines the function. {company_name}'s {count} active {'posting' if count == 1 else 'postings'} {'falls' if count == 1 else 'fall'} into the {"first hire" if count <= 2 else "build team"} category based on role count.</p>

                <p style="margin-bottom: 1.25rem;">FDE roles across the market are {na_pct}% North America-focused based on {total_jobs} active postings. {growth_pct}% of FDE roles are classified as growth hires, meaning the company is expanding its customer base rather than backfilling an existing position. This context matters for FDE candidates evaluating {company_name}: growth hire roles often come with more pressure to ramp quickly but also clearer performance metrics tied to customer success.</p>

                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">What FDEs Do at {company_name}</h2>

                <p style="margin-bottom: 1.25rem;">Forward Deployed Engineers at {company_name} own the technical success of customer deployments. This means designing integration architectures specific to each customer's infrastructure, writing and maintaining production code that runs in customer environments, and serving as the primary technical point of contact for enterprise accounts. The role sits at the intersection of product engineering and customer success without being either.</p>

                <p style="margin-bottom: 1.25rem;">Day-to-day work for an FDE at {company_name} varies by customer complexity and deployment stage. In the early phases of a new customer engagement, FDEs focus on environment setup, data mapping, and building the first integrations. As deployments mature, the work shifts toward performance tuning, expanding use cases, and training customer teams on new capabilities. Some FDE roles also feed product insights back to internal engineering, effectively acting as a bridge between customer needs and the roadmap.</p>

                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">Career Path for FDEs at {company_name}</h2>

                <p style="margin-bottom: 1.25rem;">FDE careers typically progress along one of three paths: deepening technical specialization within the FDE function (moving from mid-level to senior to staff FDE), transitioning into engineering management (leading FDE teams or broader customer engineering organizations), or lateral moves into product management (where customer-facing FDE experience is highly valued). All three paths are available at companies with established FDE programs.</p>

                <p style="margin-bottom: 1.25rem;">The FDE market median of $135,000 base salary across 134 active postings reflects a market that prices the role at a premium over equivalent-seniority software engineers at the same companies. Total compensation including equity, particularly at venture-backed companies, can be 20 to 50 percent higher than base salary. FDEs considering opportunities at {company_name} should evaluate total compensation, not just base salary, when comparing offers.</p>

                <p style="margin-bottom: 1.25rem;">Interview processes for FDE roles at most companies include a technical coding round, a system design round specific to customer deployment scenarios, and a customer scenario exercise where candidates are asked to scope a deployment, communicate trade-offs, and handle technical objections. Strong candidates combine engineering depth with the ability to explain complex systems to non-technical stakeholders clearly and without jargon.</p>'''

    body = f'''
        <section class="cp-section">
            <div class="cp-hero">
                <h1 class="cp-hero__title">Forward Deployed Engineer at {company_name}</h1>
                <div class="cp-hero__meta">
                    {count} active FDE role{"s" if count != 1 else ""}
                    {(" &middot; " + sal_range + " salary") if sal_range != "Not disclosed" else ""}
                    {(" &middot; " + loc_str) if locations else ""}
                </div>
            </div>

            <h2 class="cp-jobs-title">FDE Roles at {company_name}</h2>
            <div class="cp-jobs-list">
                {job_list_html}
            </div>

            <div class="cp-content">
                {about_fde}

                <h2 style="font-size: 1.75rem; font-weight: 700; color: var(--text-primary); margin: 2.5rem 0 1rem;">Frequently Asked Questions</h2>
                {faq_html}
            </div>

            {related}

            {get_cta_box()}

            <div class="cp-similar">
                <h2 class="cp-similar__title">Other Companies Hiring FDEs</h2>
                <div class="cp-similar__grid">
                    {similar_html}
                </div>
            </div>
        </section>'''

    # Job posting schema for first job
    job_schemas = []
    for j in co_jobs[:3]:
        title = j.get('title', 'Forward Deployed Engineer')
        mn = j.get('min_amount', 0) or 0
        mx = j.get('max_amount', 0) or 0
        jp = {
            "@context": "https://schema.org",
            "@type": "JobPosting",
            "title": title,
            "hiringOrganization": {
                "@type": "Organization",
                "name": company_name,
            },
            "jobLocation": {
                "@type": "Place",
                "address": {
                    "@type": "PostalAddress",
                    "addressLocality": (j.get('location') or '').split(',')[0].strip() or 'United States',
                    "addressCountry": "US",
                }
            },
            "datePosted": j.get('date_posted', '2026-04-30'),
            "validThrough": "2026-07-30",
            "employmentType": "FULL_TIME",
            "url": j.get('source_url', ''),
        }
        if mn > 0 and mx > 0:
            jp["baseSalary"] = {
                "@type": "MonetaryAmount",
                "currency": "USD",
                "value": {"@type": "QuantitativeValue", "minValue": mn, "maxValue": mx, "unitText": "YEAR"}
            }
        job_schemas.append(json.dumps(jp, indent=2))

    faq_schema = json.dumps({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faq_schema_list
    }, indent=2)

    breadcrumb = json.dumps({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL},
            {"@type": "ListItem", "position": 2, "name": "Companies", "item": BASE_URL + "/companies/"},
            {"@type": "ListItem", "position": 3, "name": company_name, "item": BASE_URL + "/companies/" + slug + "/"},
        ]
    }, indent=2)

    org_schema = json.dumps({
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": company_name,
        "url": BASE_URL + "/companies/" + slug + "/"
    }, indent=2)

    schema_tags = ''.join(
        f'    <script type="application/ld+json">\n{s}\n    </script>\n'
        for s in [faq_schema, breadcrumb, org_schema] + job_schemas
    )

    page_css = '''
.cp-section { max-width: 900px; margin: 0 auto; padding: 8rem 1.5rem 4rem; }
.cp-hero { margin-bottom: 2.5rem; }
.cp-hero__title { font-size: 2.5rem; font-weight: 700; margin-bottom: 0.5rem; }
.cp-hero__meta { font-size: 1rem; color: var(--text-muted); }
.cp-jobs-title { font-size: 1.5rem; font-weight: 700; color: var(--text-primary); margin-bottom: 1rem; }
.cp-jobs-list { margin-bottom: 3rem; }
.cp-job {
    display: block; background: var(--bg-card); border: 1px solid var(--border);
    border-radius: var(--radius-md); padding: 1rem 1.25rem; margin-bottom: 0.75rem;
    text-decoration: none; transition: all var(--transition-fast);
}
.cp-job:hover { background: var(--bg-card-hover); border-color: var(--amber); box-shadow: var(--shadow-glow); }
.cp-job__header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 0.5rem; gap: 0.75rem; }
.cp-job__title { font-weight: 600; color: var(--text-primary); font-size: 1.05rem; }
.cp-job__salary {
    background: rgba(74, 222, 128, 0.1); border: 1px solid rgba(74, 222, 128, 0.25);
    padding: 0.25rem 0.65rem; border-radius: var(--radius-full);
    font-size: 0.85rem; font-weight: 600; color: #4ade80; white-space: nowrap;
}
.cp-job__meta { display: flex; gap: 0.5rem; flex-wrap: wrap; align-items: center; }
.cp-job__tag {
    display: inline-flex; align-items: center; padding: 3px 10px;
    background: rgba(255,255,255,0.05); border-radius: var(--radius-full);
    font-size: 0.8rem; color: var(--text-muted);
}
.cp-job__tag--remote { background: rgba(74, 222, 128, 0.12); color: var(--success); font-weight: 500; }
.cp-job__tag--sen { background: rgba(245, 158, 11, 0.12); color: var(--amber-light); }
.cp-job__cta { margin-left: auto; font-size: 0.85rem; color: var(--amber-light); font-weight: 500; }
.cp-content { color: var(--text-secondary); font-size: 1.05rem; line-height: 1.8; margin-bottom: 2.5rem; }
.cp-similar { margin-top: 3rem; }
.cp-similar__title { font-size: 1.25rem; font-weight: 700; color: var(--text-primary); margin-bottom: 1rem; }
.cp-similar__grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 0.75rem; }
.cp-sim-card {
    display: block; background: var(--bg-card); border: 1px solid var(--border);
    border-radius: var(--radius-md); padding: 0.85rem 1rem; text-decoration: none;
    transition: all var(--transition-fast);
}
.cp-sim-card:hover { border-color: var(--amber); background: var(--bg-card-hover); }
.cp-sim-card__name { font-size: 0.9rem; font-weight: 600; color: var(--text-primary); margin-bottom: 0.2rem; }
.cp-sim-card__count { font-size: 0.8rem; color: var(--text-muted); }
@media (max-width: 768px) {
    .cp-section { padding: 6rem 1rem 3rem; }
    .cp-hero__title { font-size: 2rem; }
    .cp-job__header { flex-direction: column; }
}
'''

    extra_head = f'<style>{page_css}</style>\n{schema_tags}'

    sal_desc = f' Salary {sal_range}.' if sal_range != 'Not disclosed' else ''
    html = get_html_head(
        title=f"FDE at {company_name}: Roles, Salary, How to Apply",
        description=f"{company_name} has {count} active Forward Deployed Engineer {'role' if count == 1 else 'roles'} as of April 2026.{sal_desc} Full breakdown of open positions and what FDEs do.",
        canonical_path=f"/companies/{slug}/",
        extra_head=extra_head
    )
    html += f'''
<body>
{get_header_html()}
    <main>
{body}
    </main>
{get_footer_html()}
{get_mobile_nav_js()}
{get_signup_js()}
</body>
</html>'''

    return slug, html


def generate_company_profile_pages():
    print("  Generating company profile pages...")

    jobs_file = os.path.join(DATA_DIR, 'jobs.json')
    market_file = os.path.join(DATA_DIR, 'market_intelligence.json')

    with open(jobs_file, encoding='utf-8') as f:
        jobs_data = json.load(f)

    with open(market_file, encoding='utf-8') as f:
        market_intel = json.load(f)

    jobs = jobs_data.get('jobs', [])

    # Group jobs by company
    by_company = {}
    for j in jobs:
        comp = (j.get('company') or '').strip()
        if not comp:
            continue
        by_company.setdefault(comp, []).append(j)

    # Sort by role count descending
    sorted_companies = sorted(by_company.items(), key=lambda x: len(x[1]), reverse=True)

    count = 0
    for company_name, co_jobs in sorted_companies:
        slug = make_slug(company_name)

        # Skip curated profiles (generated by original script)
        if slug in CURATED or slug in ALREADY_GENERATED:
            continue

        slug_out, html = generate_data_driven_profile(
            company_name, co_jobs, jobs, market_intel
        )

        out_dir = os.path.join(SITE_DIR, 'companies', slug_out)
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, 'index.html')
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(html)
        count += 1

    print(f"  {count} data-driven company profile pages generated")


if __name__ == "__main__":
    generate_company_profile_pages()
